"""
world/worldgen.py
Generates terrain, caves, ores, and trees for a single chunk. Called by
World the first time a chunk is loaded. Everything here is a pure function
of (seed, world coordinates) via WorldNoise, so chunks generate identically
regardless of order - a hard requirement for infinite/streaming worlds where
neighboring chunks might load in any sequence as the player wanders.

Terrain generation is fully vectorized with numpy (profiling showed the
naive per-block Python loop took ~25ms/chunk, dominated by repeated
trig/hash calls; the vectorized version does the same math over whole
arrays in under 2ms/chunk, which is what makes crossing a chunk boundary
during normal play feel instant instead of causing a visible stutter).

Terrain is built from three layers stacked on a fixed baseline:
  1. base rolling hills   (terrain2d, low frequency - the general shape)
  2. high frequency detail (detail2d - bumps and dips so slopes don't read
     as one smooth mathematical surface)
  3. mountains            (a jittered grid of cells, at most one massif each)
plus a very coarse plains mask that flattens selected regions into open,
tree-less building ground.

Mountains are NOT a noise threshold. Thresholding a sine field (what this
used to do) gives every mountain the same silhouette and no control over
size or spacing. Instead the world is divided into cells; each cell hashes
its own centre, radius, height, profile exponent and plateau flag, so no
two massifs come out alike, and the coordinates are domain-warped first so
footprints aren't circular. See _mountain_field.

Caves: two independent 3D noise passes unioned together - narrow tunnels
plus much coarser open chambers - carved out of stone below the surface.
On steep columns only, the band is allowed up to the surface block so
passages open as dark holes in cliff faces (never as pits in flat ground).
Ores: coal scattered through stone (denser inside mountains), iron rarer
and restricted to lower layers - mirrors the balance tuned in the JS build
(coal ~2x more common than iron after testing).
Trees: placed on grass columns with a per-column chance, skipped on plains,
on stone summits, and on steep slopes (so mountains only grow trees on
their terraces). Kept away from chunk edges where neighbor data is
guaranteed local (leaves may reach one block into a neighboring chunk -
handled by the caller via a leaf queue).

NOTE ON EXISTING WORLDS: chunks already written to disk are loaded verbatim
by World._get_or_create_chunk and never re-run through this module, so
player builds are untouched by any change here. The cost is that terrain
generated by an older version of this file won't line up with terrain
generated by this one, leaving a seam at the edge of previously-explored
area. That is a known, accepted trade-off.
"""

import math
import numpy as np

from world.blocks import Block
from world.chunk import Chunk, CX, CZ, CH
from world.noise import WorldNoise
import config


# --- mountains --------------------------------------------------------------

def _mountain_field(noise: WorldNoise, WX: np.ndarray, WZ: np.ndarray):
    """
    Evaluates the mountain layer for a grid of world coordinates. Returns
    three arrays shaped like WX:

      add   - blocks of mountain rise for this column
      peak  - the dominant massif's full rise (its summit height above the
              surrounding ground), used to decide where stone caps start
      infl  - 0..1, how deep inside that massif's footprint this column is

    The world is tiled into cells of config.MOUNTAIN_CELL_SIZE blocks. Each
    cell holds at most one massif, and *every* property of that massif is
    hashed from the cell coordinate: whether it exists at all, where inside
    the cell its centre sits, its radius, its height, how sharp its profile
    is, and whether its summit is sheared into a plateau. Nothing here reads
    global state or depends on load order, so a massif straddling four
    chunks generates identically no matter which chunk arrives first.

    Only the 3x3 neighbourhood of cells is tested per column: a massif's
    influence radius is at most MOUNTAIN_RADIUS_MAX * MOUNTAIN_FOOTHILL_FACTOR
    (96 blocks by default), comfortably under one 400-block cell, so no
    massif outside that ring can possibly reach the column.
    """
    cell = float(config.MOUNTAIN_CELL_SIZE)
    warp = config.MOUNTAIN_WARP_STRENGTH

    # Warp the sample point before any distance math. The falloff below is a
    # radial function, which on raw coordinates draws perfect circles; warping
    # the input bends those outlines into ridges, spurs and hollows.
    PX = WX + noise.warp_grid(WX, WZ, 0) * warp
    PZ = WZ + noise.warp_grid(WX, WZ, 1) * warp

    base_cx = np.floor(PX / cell)
    base_cz = np.floor(PZ / cell)

    best_add = np.zeros(PX.shape, dtype=np.float64)
    best_peak = np.zeros(PX.shape, dtype=np.float64)
    best_infl = np.zeros(PX.shape, dtype=np.float64)

    for dcx in (-1, 0, 1):
        for dcz in (-1, 0, 1):
            ccx = (base_cx + dcx).astype(np.int64)
            ccz = (base_cz + dcz).astype(np.int64)

            # Independent hashes per property - a single hash per cell would
            # correlate radius with height with position and make every
            # massif a scaled copy of the same shape.
            roll_present = noise.hash2_salted_grid(ccx, ccz, 3)
            jitter_x = noise.hash2_salted_grid(ccx, ccz, 11)
            jitter_z = noise.hash2_salted_grid(ccx, ccz, 23)
            roll_radius = noise.hash2_salted_grid(ccx, ccz, 37)
            roll_height = noise.hash2_salted_grid(ccx, ccz, 53)
            roll_profile = noise.hash2_salted_grid(ccx, ccz, 71)
            roll_flat = noise.hash2_salted_grid(ccx, ccz, 89)
            roll_angle = noise.hash2_salted_grid(ccx, ccz, 103)
            roll_aspect = noise.hash2_salted_grid(ccx, ccz, 107)
            roll_ridge_n = noise.hash2_salted_grid(ccx, ccz, 109)
            roll_ridge_phase = noise.hash2_salted_grid(ccx, ccz, 113)

            # Keep centres inside the middle 60% of the cell: a centre sitting
            # right on a cell edge could fuse with its neighbour into one
            # endless ridge, which is exactly the "all mountains look the
            # same" failure we're avoiding.
            centre_x = (ccx + 0.2 + jitter_x * 0.6) * cell
            centre_z = (ccz + 0.2 + jitter_z * 0.6) * cell

            # Which KIND of massif this is gets sampled at the cell CENTRE,
            # never per column. Sampling per column would let one massif start
            # rounded on its south flank and rear up as a spire on its north
            # one, with a seam through the middle where the mask crossed the
            # threshold. Kind is a property of the mountain, not of the ground
            # you happen to be standing on.
            is_alpine = noise.alpine_mask_grid(centre_x, centre_z) > config.ALPINE_THRESHOLD

            # Whether this cell is on land is likewise sampled at the CENTRE,
            # never per column, and for exactly the reason the alpine test is:
            # a mountain either exists or it does not. Scaling a massif's
            # height by per-column continentalness instead would let one
            # mountain fade out across its own western slope, and - worse -
            # would drag m_peak across the alpine/rounded classification cut
            # midway through the same massif, speckling it with two different
            # summit rules. Gating presence keeps every massif whole; a coastal
            # one still runs down into the sea naturally, because the terrain
            # baseline it is built on has already dropped.
            centre_land = noise.continent_grid(centre_x, centre_z) > config.OCEAN_THRESHOLD

            present = (roll_present < np.where(
                is_alpine, config.ALPINE_CELL_FILL, config.MOUNTAIN_CELL_FILL
            )) & centre_land

            radius = np.where(
                is_alpine,
                config.ALPINE_RADIUS_MIN + roll_radius * (config.ALPINE_RADIUS_MAX - config.ALPINE_RADIUS_MIN),
                config.MOUNTAIN_RADIUS_MIN + roll_radius * (config.MOUNTAIN_RADIUS_MAX - config.MOUNTAIN_RADIUS_MIN),
            )
            peak = np.where(
                is_alpine,
                config.ALPINE_HEIGHT_MIN + roll_height * (config.ALPINE_HEIGHT_MAX - config.ALPINE_HEIGHT_MIN),
                config.MOUNTAIN_HEIGHT_MIN + roll_height * (config.MOUNTAIN_HEIGHT_MAX - config.MOUNTAIN_HEIGHT_MIN),
            )
            profile = np.where(
                is_alpine,
                config.ALPINE_PROFILE_MIN + roll_profile * (config.ALPINE_PROFILE_MAX - config.ALPINE_PROFILE_MIN),
                config.MOUNTAIN_PROFILE_MIN + roll_profile * (config.MOUNTAIN_PROFILE_MAX - config.MOUNTAIN_PROFILE_MIN),
            )
            foothill = np.where(is_alpine, config.ALPINE_FOOTHILL_FACTOR, config.MOUNTAIN_FOOTHILL_FACTOR)

            # --- footprint: a rotated ellipse chewed into by radial spurs ---
            # Distance-to-centre draws a circle, and scaling that circle by
            # radius/height/profile still leaves every massif the SAME
            # silhouette at a different size - which is exactly why they read
            # as one mountain stamped over and over. The global domain warp
            # above bends all of them, but it bends neighbours the same way,
            # so it can't separate them either. These three do: the footprint
            # becomes an ellipse at a hashed rotation, with a hashed number of
            # spurs cut into its outline at a hashed phase. Every factor is
            # continuous and drawn from the cell coordinate, so the odds of
            # two massifs anywhere in an infinite world sharing all of
            # rotation, aspect, spur count, spur phase, radius, height and
            # profile are nil.
            dx = PX - centre_x
            dz = PZ - centre_z

            angle = roll_angle * 6.283185307
            ca = np.cos(angle)
            sa = np.sin(angle)
            rx = dx * ca + dz * sa
            rz = -dx * sa + dz * ca

            aspect = (config.MOUNTAIN_ASPECT_MIN
                      + roll_aspect * (config.MOUNTAIN_ASPECT_MAX - config.MOUNTAIN_ASPECT_MIN))
            rx = rx / aspect
            rz = rz * aspect

            dist = np.sqrt(rx * rx + rz * rz)

            # Spurs: modulate the effective radius as a function of the angle
            # around the centre, so ridges run down the flanks and gullies bite
            # in between them. Amplitude stays under 1.0 so `outer` can never
            # reach zero and divide out below.
            ridge_count = np.round(
                config.MOUNTAIN_RIDGE_COUNT_MIN
                + roll_ridge_n * (config.MOUNTAIN_RIDGE_COUNT_MAX - config.MOUNTAIN_RIDGE_COUNT_MIN)
            )
            theta = np.arctan2(rz, rx)
            ridge = 1.0 + config.MOUNTAIN_RIDGE_AMPLITUDE * np.sin(
                theta * ridge_count + roll_ridge_phase * 6.283185307
            )

            outer = radius * foothill * ridge

            # smoothstep: derivative is zero at both ends, so the massif
            # emerges from the plain gently (the foothill) and rounds off at
            # the top instead of meeting flat ground at a hard crease.
            t = np.clip(1.0 - dist / outer, 0.0, 1.0)
            infl = t * t * (3.0 - 2.0 * t)

            # The exponent is what makes silhouettes differ: near 1.7 the
            # massif is broad-shouldered, near 3.2 it's a narrow spire, and an
            # alpine 4.5-6.0 keeps the flanks low until they rear up hard into
            # the summit - the steep, sudden shape, and the only thing in the
            # world that produces slopes past CAVE_ENTRANCE_SLOPE.
            add = (infl ** profile) * peak

            # A minority of ROUNDED massifs get their summit sheared into a
            # plateau. Alpine peaks are excluded: flattening the top off the
            # one shape whose entire point is a sharp summit defeats it.
            is_plateau = (roll_flat < config.MOUNTAIN_PLATEAU_CHANCE) & ~is_alpine
            ceiling = peak * config.MOUNTAIN_PLATEAU_LEVEL
            add = np.where(is_plateau, np.minimum(add, ceiling), add)
            # Report the height actually reachable, not the nominal peak -
            # otherwise a plateau's "depth below summit" never hits zero and
            # its top would never get a stone cap.
            effective_peak = np.where(is_plateau, ceiling, peak)

            add = np.where(present, add, 0.0)
            infl = np.where(present, infl, 0.0)
            effective_peak = np.where(present, effective_peak, 0.0)

            # Where two massifs overlap the taller one wins; this is also
            # what lets two nearby cells read as one twin-peaked mountain.
            better = add > best_add
            best_add = np.where(better, add, best_add)
            best_peak = np.where(better, effective_peak, best_peak)
            best_infl = np.where(better, infl, best_infl)

    return best_add, best_peak, best_infl


# --- per-column height ------------------------------------------------------

def _column_fields(noise: WorldNoise, WX: np.ndarray, WZ: np.ndarray):
    """
    Computes every per-column quantity the generator needs, for an arbitrary
    grid of world coordinates. Returns (heights, m_add, m_peak, m_infl,
    plains_w, land_w).

    land_w is 0 on the open seabed and 1 fully inland, ramping across the
    continental shelf; the shoreline sits at land_w = (SEA_LEVEL -
    OCEAN_FLOOR_HEIGHT) / (BASE_TERRAIN_HEIGHT - OCEAN_FLOOR_HEIGHT). Beaches
    and (later) rivers key off it.

    Factored out so the exact same code path serves three callers: the real
    chunk generator, the padded border ring it needs for slope measurement,
    and the scalar terrain_height() used by tools. Anything that samples
    height goes through here, so the values can never drift apart.
    """
    # layer 1: base rolling hills
    terrain_n = noise.terrain2d_grid(WX, WZ)
    hills = (terrain_n / 4.5) * config.HILL_AMPLITUDE

    # layer 2: high frequency roughness
    detail = noise.detail2d_grid(WX, WZ) * config.DETAIL_AMPLITUDE

    # layer 3: mountains
    m_add, m_peak, m_infl = _mountain_field(noise, WX, WZ)

    # plains mask, weighted so it fades in over PLAINS_FALLOFF rather than
    # switching on at a hard edge (which would leave a visible step)
    plains_raw = noise.plains_mask_grid(WX, WZ)
    plains_w = np.clip((plains_raw - config.PLAINS_THRESHOLD) / config.PLAINS_FALLOFF, 0.0, 1.0)

    # A massif always beats a plain. The two masks are independent, so
    # without this a mountain unlucky enough to land inside the plains mask
    # would get its own hills flattened out from under it.
    plains_w = plains_w * (1.0 - np.clip(m_infl * 2.5, 0.0, 1.0))

    keep = 1.0 - plains_w * (1.0 - config.PLAINS_FLATNESS)
    hills = hills * keep
    detail = detail * keep

    # layer 0: continentalness. Ramps the BASELINE the other layers sit on,
    # between the open seabed and the inland surface. Relief is damped in the
    # same ramp - fully offshore the seabed keeps only OCEAN_RELIEF_KEEP of its
    # hills, so it reads as a seabed rather than as drowned countryside, while
    # near the shore enough survives to chew the coastline into bays and
    # headlands instead of tracing the mask's contour line.
    cont = noise.continent_grid(WX, WZ)
    land_w = np.clip((cont - config.OCEAN_THRESHOLD) / config.OCEAN_FALLOFF, 0.0, 1.0)
    baseline = config.OCEAN_FLOOR_HEIGHT + (
        config.BASE_TERRAIN_HEIGHT - config.OCEAN_FLOOR_HEIGHT
    ) * land_w
    relief = config.OCEAN_RELIEF_KEEP + (1.0 - config.OCEAN_RELIEF_KEEP) * land_w
    hills = hills * relief
    detail = detail * relief

    h = baseline + hills + detail + m_add

    # Terraces. Quantizing height to TERRACE_STEP automatically produces the
    # behaviour the design asks for - wide steps on gentle ground, narrow
    # ones where the underlying slope is steep - because the tread width is
    # just the horizontal distance the raw height takes to climb one step.
    # Blended in by influence so terracing stops at the foot of the massif
    # instead of stepping the surrounding plain.
    terraced = np.floor(h / config.TERRACE_STEP) * config.TERRACE_STEP
    terrace_w = np.clip((m_infl - config.TERRACE_MIN_INFLUENCE) / config.TERRACE_FALLOFF, 0.0, 1.0)
    h = h * (1.0 - terrace_w) + terraced * terrace_w

    heights = np.clip(np.round(h), 4, CH - 20).astype(np.int32)
    return heights, m_add, m_peak, m_infl, plains_w, land_w


def terrain_height(noise: WorldNoise, wx: int, wz: int):
    """Scalar single-point height query (used by tools/tests, not the hot path).
    Delegates to _column_fields so it can never disagree with the real
    generator. Returns (height, is_mountain)."""
    WX = np.array([[float(wx)]], dtype=np.float64)
    WZ = np.array([[float(wz)]], dtype=np.float64)
    heights, _m_add, _m_peak, m_infl, _plains, _land = _column_fields(noise, WX, WZ)
    return int(heights[0, 0]), bool(m_infl[0, 0] > config.MOUNTAIN_ORE_INFLUENCE)


# --- chunk terrain ----------------------------------------------------------

def generate_chunk_terrain(chunk: Chunk, noise: WorldNoise):
    """Fills base terrain (grass/dirt/stone), applies stone summit caps,
    carves caves, and scatters ores - fully vectorized."""
    ox, oz = chunk.world_origin()

    # Height fields over a 1-block padded ring around the chunk. The padding
    # exists so each column's slope can be measured against its true
    # neighbours even at the chunk border. Because heights are a pure
    # function of world position, the ring values computed here are
    # bit-identical to what the adjacent chunk computes for itself - so
    # slope (and therefore cave-entrance placement) never disagrees across
    # a chunk seam, no matter which of the two generates first.
    pad_x = np.arange(-1, CX + 1)
    pad_z = np.arange(-1, CZ + 1)
    PLX, PLZ = np.meshgrid(pad_x, pad_z, indexing="ij")
    PWX = (PLX + ox).astype(np.float64)
    PWZ = (PLZ + oz).astype(np.float64)

    p_heights, p_add, p_peak, p_infl, _p_plains, p_land = _column_fields(noise, PWX, PWZ)

    heights = p_heights[1:-1, 1:-1]
    m_add = p_add[1:-1, 1:-1]
    m_peak = p_peak[1:-1, 1:-1]
    m_infl = p_infl[1:-1, 1:-1]
    land_w = p_land[1:-1, 1:-1]
    WX = PWX[1:-1, 1:-1]
    WZ = PWZ[1:-1, 1:-1]

    # steepest drop to any of the four orthogonal neighbours, in blocks
    slope = np.maximum.reduce([
        np.abs(heights - p_heights[0:-2, 1:-1]),
        np.abs(heights - p_heights[2:, 1:-1]),
        np.abs(heights - p_heights[1:-1, 0:-2]),
        np.abs(heights - p_heights[1:-1, 2:]),
    ])

    chunk.height_map[:, :] = heights
    # Snapshot the natural surface before a single block is placed on top of
    # it. height_map tracks the topmost SOLID block and so stops describing the
    # ground the moment anything is built or grown there; terrain_height keeps
    # the generator's answer forever. See Chunk.build_shadow_spots.
    chunk.terrain_height[:, :] = heights
    # The column array has to reach the water line even where no terrain does:
    # in open ocean heights.max() is around the seabed, well under SEA_LEVEL,
    # and sizing the array to it would leave nowhere to put the sea.
    max_h = max(int(heights.max()), config.SEA_LEVEL)

    # --- base terrain fill: grass/dirt/stone per column up to that column's height ---
    y_range = np.arange(0, max_h + 1)
    Y = y_range.reshape(1, 1, -1)
    H = heights.reshape(CX, CZ, 1)
    within_column = Y <= H

    is_top = (Y == H) & within_column
    is_dirt_band = (Y >= (H - 3)) & within_column & ~is_top
    is_stone = within_column & ~is_top & ~is_dirt_band

    block_grid = np.zeros((CX, CZ, max_h + 1), dtype=np.uint8)
    block_grid[is_stone] = Block.STONE
    block_grid[is_dirt_band] = Block.DIRT
    block_grid[is_top] = Block.GRASS

    # --- stone near summits ---------------------------------------------------
    # Measured as depth below THIS massif's own summit rather than as an
    # absolute world height: a 30-block massif and a 40-block one should both
    # be bare rock at the top and green at the bottom, which an absolute
    # cutoff can't express.
    depth_from_peak = m_peak - m_add
    on_massif = m_peak > 0.5

    # Alpine massifs are identified here by their peak height rather than by
    # threading another array out of _mountain_field: the two height ranges
    # (rounded 30-40, alpine 80-120) don't overlap, so the midpoint separates
    # them exactly, and m_peak is already constant across a massif.
    alpine_peak_cut = (config.MOUNTAIN_HEIGHT_MAX + config.ALPINE_HEIGHT_MIN) * 0.5
    is_alpine_col = m_peak > alpine_peak_cut

    # Whether a massif goes bare near the top is a property OF THAT MASSIF and
    # must be constant across the whole of it - a per-column roll would speckle
    # one mountain with random rock. m_peak is already exactly such a value:
    # one number per dominant massif, continuous, effectively unique. Taking
    # its fractional part after a prime-ish scale turns it into a stable
    # per-mountain roll for free.
    rock_roll = np.modf(np.abs(m_peak) * 137.71)[0]
    is_rocky = on_massif & (rock_roll < config.MOUNTAIN_ROCKY_CHANCE)

    # Alpine peaks strip back further than rounded ones, but the transition
    # band keeps the width it was tuned at, so this can't invert into
    # cap_depth > mix_depth however those two constants are later retuned.
    cap_depth = np.where(is_alpine_col, config.ALPINE_STONE_DEPTH, config.STONE_CAP_DEPTH)
    mix_depth = cap_depth + float(config.STONE_MIX_DEPTH - config.STONE_CAP_DEPTH)

    cap = is_rocky & (depth_from_peak <= cap_depth)
    mix_span = np.maximum(1e-6, mix_depth - cap_depth)
    mix_ratio = np.clip((mix_depth - depth_from_peak) / mix_span, 0.0, 1.0)
    # Probabilistic dithering through the transition band so grass gives way
    # to rock as a ragged scatter rather than a drawn contour line.
    mix_roll = noise.hash2_grid(WX + 7777.0, WZ - 7777.0)
    in_mix_band = is_rocky & (depth_from_peak <= mix_depth)
    stone_surface = cap | (in_mix_band & (mix_roll < mix_ratio))

    stone_col = stone_surface.reshape(CX, CZ, 1)
    soil = (block_grid == Block.GRASS) | (block_grid == Block.DIRT)
    block_grid = np.where(stone_col & soil, np.uint8(Block.STONE), block_grid).astype(np.uint8)

    # --- shoreline material: sand instead of soil at and under the water line ---
    # Minecraft expresses this as a Beach biome, but the rule the biome
    # actually encodes is just "ground that meets the sea is sand", which is
    # what this reproduces without needing a biome layer at all.
    #
    # TWO tests, and both are load-bearing:
    #
    #   land_w  - is this column anywhere near the sea at all? Without it the
    #             height test alone put sand in the floor of every inland
    #             valley in the world (see config.BEACH_BASELINE_RISE), because
    #             inland terrain bottoms out at exactly SEA_LEVEL + BEACH_RISE
    #             while the water fill needs to be lower still. Dry sand discs
    #             in the middle of grassland, nowhere near an ocean.
    #
    #   heights - where exactly does the sand stop? Keyed on the column's own
    #             surface rather than on land_w so the beach follows the real,
    #             relief-chewed coastline: a headland standing a few blocks
    #             proud of the water keeps its grass, the cove beside it goes
    #             sandy. Gating on land_w alone would trace a smooth contour of
    #             the continentalness mask, which is exactly the ruler-drawn
    #             look this is supposed to avoid.
    sandy_col = (
        (land_w <= config.BEACH_MAX_LAND_W)
        & (heights <= config.SEA_LEVEL + config.BEACH_RISE)
    ).reshape(CX, CZ, 1)
    block_grid = np.where(sandy_col & soil, np.uint8(Block.SAND), block_grid).astype(np.uint8)

    # --- caves + ore scattering, vectorized over the same (CX, CZ, max_h+1) volume ---
    ones_col = np.ones((1, 1, max_h + 1), dtype=np.float64)
    WX3 = WX.reshape(CX, CZ, 1) * ones_col
    WZ3 = WZ.reshape(CX, CZ, 1) * ones_col
    Y3 = np.broadcast_to(y_range.reshape(1, 1, -1), (CX, CZ, max_h + 1))

    steep = slope >= config.CAVE_ENTRANCE_SLOPE
    steep_col = steep.reshape(CX, CZ, 1)

    # On a cliff the band reaches the block just under the surface, so a
    # passage running into the slope opens as a dark hole beneath an
    # overhanging lip of grass - and because the neighbouring column is
    # several blocks lower, that hole is exposed sideways on the cliff face.
    # Everywhere else it stops 3 blocks short, which is what keeps caves
    # from hollowing out flat ground and summits from above.
    cave_top = np.where(steep, heights, heights - 3).reshape(CX, CZ, 1)
    in_cave_band = (Y3 >= 1) & (Y3 < cave_top)

    cave_n = noise.cave3d_grid(WX3, Y3, WZ3)
    cavern_n = noise.cavern3d_grid(WX3, Y3, WZ3)
    # Union of two independent frequency bands: tight winding tunnels from
    # the fine pass, standable chambers from the coarse one.
    hollow = (cave_n > config.CAVE_THRESHOLD) | (cavern_n > config.CAVERN_THRESHOLD)
    # Both thresholds are measured values - see the calibration note in config.

    # Soil is only carvable on cliff columns. Without this an entrance would
    # stop dead against the 3-block dirt shell and never actually open.
    carvable = (block_grid == Block.STONE) | (
        steep_col & ((block_grid == Block.DIRT) | (block_grid == Block.GRASS))
    )
    block_grid[carvable & in_cave_band & hollow] = Block.AIR

    still_stone = (block_grid == Block.STONE) & in_cave_band
    ore_roll = noise.hash3_grid(WX3, Y3, WZ3)

    mountain_col = (m_infl > config.MOUNTAIN_ORE_INFLUENCE).reshape(CX, CZ, 1)
    coal_chance = np.where(mountain_col, config.ORE_CHANCE_COAL_MOUNTAIN, config.ORE_CHANCE_COAL)
    coal_band = still_stone & (Y3 < (heights.reshape(CX, CZ, 1) - 4)) & (ore_roll < coal_chance)
    block_grid[coal_band] = Block.COAL_ORE

    iron_band = still_stone & (~coal_band) & (Y3 < 10) & (ore_roll < config.ORE_CHANCE_IRON)
    block_grid[iron_band] = Block.IRON_ORE

    # --- fill the sea ---
    # Strictly a per-column fill from the terrain surface up to the water line,
    # NOT "every air cell below SEA_LEVEL". The distinction is the whole
    # difference between an ocean and a flooded world: caves are carved below
    # the surface, so a blanket fill would drown every cavern under every
    # coastline and turn the underground into an aquifer.
    #
    # A consequence, and it is the correct one: a cave that a cliff-side
    # entrance opens below the water line stays DRY, because nothing here fills
    # it and worldgen water never flows (it is written straight into the array,
    # with no neighbour updates - see World.set_block's update_neighbors flag).
    # Minecraft before 1.18 behaves identically, which is why dry caves under
    # the sea are a normal thing to find there.
    water_band = (Y3 > heights.reshape(CX, CZ, 1)) & (Y3 <= config.SEA_LEVEL)
    block_grid[water_band] = Block.WATER

    # --- write into the chunk's flat block array ---
    flat_dest = chunk.blocks.reshape(CH, CZ, CX)  # matches _idx: x + z*CX + y*CX*CZ
    flat_dest[0:max_h + 1, :, :] = np.transpose(block_grid, (2, 1, 0))

    chunk.generated = True


def _flat_idx(x: int, y: int, z: int) -> int:
    return x + z * CX + y * CX * CZ


# --- Tree generation --------------------------------------------------------
# (kept scalar: trees are sparse point features, not worth vectorizing, and
# need sequential logic - checking the surface block, computing trunk height
# from a second hash - that reads more clearly as a simple per-column loop)

TREE_TRUNK_HEIGHT_MIN = 4
TREE_TRUNK_HEIGHT_MAX = 6


def tree_columns_for_chunk(chunk: Chunk, noise: WorldNoise):
    """
    Decides which local (lx, lz) columns in this chunk should grow a tree,
    based on a per-column hashed chance. Kept as a separate deterministic
    step (rather than being folded into terrain gen) so World can call it
    once neighbor height data is available, and so leaves/logs can be
    placed via set_block calls that correctly cross chunk borders.

    Three rejections happen before the chance roll:
      - plains get a much lower tree chance instead of being left bare, so
        they read as clearings rather than as an abrupt end of the forest
      - the surface must still be grass, which excludes stone summits and
        any column a cave entrance has just been carved through
      - the column must be flat enough, which on a mountain means trees only
        take hold on the terraces and never on the steep faces between them
    """
    ox, oz = chunk.world_origin()

    local_x = np.arange(CX)
    local_z = np.arange(CZ)
    LX, LZ = np.meshgrid(local_x, local_z, indexing="ij")
    plains_raw = noise.plains_mask_grid((LX + ox).astype(np.float64), (LZ + oz).astype(np.float64))
    is_plains = plains_raw > config.PLAINS_THRESHOLD

    height_map = chunk.height_map
    spots = []
    for lx in range(2, CX - 2):  # keep trees off the very edge to reduce cross-chunk leaf spill
        for lz in range(2, CZ - 2):
            wx, wz = ox + lx, oz + lz
            top = int(height_map[lx, lz])
            surface_block = chunk.get_local(lx, top, lz)
            if surface_block != Block.GRASS:
                continue

            # lx/lz never touch the array edge here, so all four neighbours
            # are in-chunk and no cross-chunk lookup is needed
            slope = max(
                abs(top - int(height_map[lx - 1, lz])),
                abs(top - int(height_map[lx + 1, lz])),
                abs(top - int(height_map[lx, lz - 1])),
                abs(top - int(height_map[lx, lz + 1])),
            )
            if slope > config.TREE_MAX_SLOPE:
                continue

            # Plains are thinned out, not shaved bald. A hard skip here left
            # them reading as an artificial green desert with a visible line
            # where the forest stopped dead; a low chance keeps them open and
            # buildable while still looking like ground trees could grow on.
            chance = config.TREE_CHANCE_PLAINS if is_plains[lx, lz] else config.TREE_CHANCE
            roll = noise.hash2(wx, wz)
            if roll < chance:
                trunk_height = TREE_TRUNK_HEIGHT_MIN + int(
                    noise.hash2(wx + 1000, wz + 1000) * (TREE_TRUNK_HEIGHT_MAX - TREE_TRUNK_HEIGHT_MIN + 1)
                )
                spots.append((lx, top, lz, trunk_height))
    return spots


def tree_block_offsets(trunk_height: int):
    """
    Yields (dx, dy, dz, block_id) offsets from the base of a tree (the grass
    block the trunk stands on, dy=1 is the first log) for a simple round
    Alpha-style tree: a straight log trunk topped with a blob of leaves.
    """
    offsets = []
    for dy in range(1, trunk_height + 1):
        offsets.append((0, dy, 0, Block.WOOD_LOG))

    # leaf canopy: a few layers, wider in the middle, matching Alpha's blocky trees
    top = trunk_height
    canopy_layers = [
        (top - 2, 2), (top - 1, 2), (top, 1), (top + 1, 1),
    ]
    for dy, radius in canopy_layers:
        for dx in range(-radius, radius + 1):
            for dz in range(-radius, radius + 1):
                if dx == 0 and dz == 0 and dy <= top:
                    continue  # don't overwrite the trunk itself
                dist = math.sqrt(dx * dx + dz * dz)
                if dist <= radius + 0.4:
                    offsets.append((dx, dy, dz, Block.LEAVES))
    return offsets
